// <auto-generated />
namespace Kztek.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class k10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(k10));
        
        string IMigrationMetadata.Id
        {
            get { return "201808010120088_k10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
