// <auto-generated />
namespace Kztek.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class k14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(k14));
        
        string IMigrationMetadata.Id
        {
            get { return "201808060320345_k14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
