IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'InvoiceBAVI')
BEGIN

CREATE TABLE [dbo].[InvoiceBAVI](
	[Id] [VARCHAR](128) NOT NULL,
    [EventId] [nvarchar](500) NULL,
	[DateCreated] [datetime] NOT NULL,
	[IsSync] [int] NOT NULL DEFAULT(0),

 CONSTRAINT [PK_InvoiceBAVI] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

END