
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NoteFreeTRANSERCO')
BEGIN
	CREATE TABLE [dbo].NoteFreeTRANSERCO(
	[Id] [nvarchar](128) NOT NULL,
	Note [nvarchar](max) NULL,
	
 CONSTRAINT [PK_dbo.NoteFreeTRANSERCO] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tblCardEventDelete')
BEGIN
	CREATE TABLE [dbo].tblCardEventDelete(
	[Id] [nvarchar](128) NOT NULL,
	[EventId] [nvarchar](max) NULL,
	[UserId] [nvarchar](max) NULL,
	[DateCreated] [datetime] NULL,
 CONSTRAINT [PK_dbo.tblCardEventDelete] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PayIn')
BEGIN
	CREATE TABLE [dbo].PayIn(
	[ID] int IDENTITY(1,1),
	[EventID] [nvarchar](100) NULL,
	[Moneys] numeric(18,0) NOT NULL default(0),
	[PayState] int NOT NULL default (1),
 CONSTRAINT [PK_dbo.PayIn] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
END

